-- MySQL Script generated by MySQL Workbench
-- Sun May 29 21:28:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuário` (
  `idusuário` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `e-mail` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `data de nascimento` DATE NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `usuário_idusuário` INT NOT NULL,
  PRIMARY KEY (`idEndereço`),
  INDEX `fk_endereço_usuário1_idx` (`usuário_idusuário` ASC) VISIBLE,
  CONSTRAINT `fk_endereço_usuário1`
    FOREIGN KEY (`usuário_idusuário`)
    REFERENCES `mydb`.`usuário` (`idusuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoProduto` (
  `idtipoProduto` INT NOT NULL AUTO_INCREMENT,
  `tipoProduto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoconsole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoconsole` (
  `idtipoconsole` INT NOT NULL,
  `tipoconsole` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoconsole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `tipoProduto_idtipoProduto` INT NOT NULL,
  `tipoconsole_idtipoconsole` INT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_tipoProduto1_idx` (`tipoProduto_idtipoProduto` ASC) VISIBLE,
  INDEX `fk_produto_tipoconsole1_idx` (`tipoconsole_idtipoconsole` ASC) VISIBLE,
  CONSTRAINT `fk_produto_tipoProduto1`
    FOREIGN KEY (`tipoProduto_idtipoProduto`)
    REFERENCES `mydb`.`tipoProduto` (`idtipoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_tipoconsole1`
    FOREIGN KEY (`tipoconsole_idtipoconsole`)
    REFERENCES `mydb`.`tipoconsole` (`idtipoconsole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `usuário_idusuário` INT NOT NULL,
  `data_pedido` VARCHAR(45) NOT NULL,
  `valor_total` VARCHAR(45) NOT NULL,
  `usuário_idusuário1` INT NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `fk_pedidos_usuário1_idx` (`usuário_idusuário1` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuário1`
    FOREIGN KEY (`usuário_idusuário1`)
    REFERENCES `mydb`.`usuário` (`idusuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos_has_produto` (
  `pedidos_idpedidos` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`pedidos_idpedidos`, `produto_idproduto`),
  INDEX `fk_pedidos_has_produto_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_pedidos_has_produto_pedidos1_idx` (`pedidos_idpedidos` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_produto_pedidos1`
    FOREIGN KEY (`pedidos_idpedidos`)
    REFERENCES `mydb`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
